ascorbic/unpic-img

packages/core/src/core.ts

When using a custom transform the `getSrcSet` is not using the custom one that we pass on the `transformer` prop, with this change, if we pass a custom transformer the function can use it

fix: pass `transformer` to srcset generate function

---

packages/svelte/package.json

This field is only needed if you have more than one entry point, which this package doesn't have.
Great library btw 🙌

fix(svelte): remove obsolete typesVersions

---

packages/webc/README.md

Per docs on https://www.11ty.dev/docs/languages/webc/#webcimport the component name must match the WebC file name in the package
This isn’t the only option as you can deep link to the component file name in the import if you want, see reply here:
https://fediverse.zachleat.com/@zachleat/109948320190919977

chore: fix WebC component tag name in README

---

packages/core/src/core.ts

Currently the aspect ratio is being incorrectly calculated as it's inverting it to the opposite of what's desired.
Reproduction: https://codesandbox.io/s/unpic-img-incorrect-aspect-ratio-nblkgn
Fixes #53

fix(core): fix aspect ratio calculation for srcset

---

packages/svelte/.prettierrc
packages/svelte/CHANGELOG.md
packages/svelte/README.md
packages/svelte/package.json
packages/svelte/src/app.html
packages/svelte/src/lib/image.svelte
packages/svelte/svelte.config.js
packages/svelte/tsconfig.json
packages/svelte/vite.config.ts
yarn.lock

Can't declare variables with `const` in Svelte or they won't be reactive. You need to use `$:`

chore: setup prettier-plugin-svelte

---

packages/angular/package.json
packages/astro/package.json
packages/core/package.json
packages/preact/package.json
packages/qwik/package.json
packages/react/package.json
packages/solid/package.json
packages/svelte/package.json
packages/vue/package.json
packages/webc/package.json

Adds support for [package provencance](https://github.blog/2023-04-19-introducing-npm-package-provenance/). I'm not sure if it will work with pnpm, but there's only one way to find out!

chore: add support for package provenance

---

packages/react/src/camelize.ts
packages/react/test/react.test.tsx

React treats `data-` and `aria-` attributes differently from other attributes, which it camel-cases. This PR ensures we special-case these. Fixes #215

fix(react): correctly handle aria and data attributes

---

packages/core/src/core.ts

Ensure than when the cdn is explicitly passed to the component that it is forwarded to getSrcSet
Fixes #228

fix(core): pass cdn prop to srcset

---

packages/svelte/package.json
packages/svelte/src/lib/image.svelte
packages/svelte/src/lib/index.ts
packages/svelte/src/lib/types.ts
pnpm-lock.yaml

The Svelte compiler was swallowing an error which was preventing the image.svelte.d.ts file from being generated. The error was because of what seems to be a bug in the svelte2tsx compiler. This is fixed by importing, unused, the types needed from the unpic package.

fix(svelte): generate types for svelte component

---

packages/react/src/next.tsx

pnpm has trouble with deep imports that don't have include extensions when using pnpm. This adds `.js` to all of the deep imports from Next.js.
Fixes #118

fix(react): use extension for next deep imports

---

packages/core/src/core.ts

Currently if a canonical CDN can't be resolved then a srcset isn't generated. This PR changes the logic to still generate the srcset if a transformer function has been provided.
Fixes #275

fix: always generate srcset if transformer is provided

---

docs/src/content/img/lit.md
packages/lit/README.md
packages/lit/src/unpic-img.ts

Unfortunately, it is currently not possible to apply custom styles to the Lit `unpic-img` web component. We need to use the [::part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) CSS pseudo-element to target specific elements within the shadow DOM. This pull request allows to apply styles to the `img` element, example:
```css
unpic-img::part(image) {
border-radius: 8px;
}
```

fix(lit): add css part pseudo-element

---

packages/core/src/core.ts
packages/core/test/core.test.tsx
packages/core/tsconfig.json
packages/react/tsconfig.json

Currently `transformProps` throws if there is a missing url. This PR handles it more gracefully. It also prevents logs in production by using a log wrapper.

fix(core): gracefully handle missing props

---

packages/angular/src/lib/unpic-image.directive.ts
packages/angular/src/lib/unpic-source.directive.ts

I have been trying this component in an Angular app, and I noticed a lot of console messages like
```
img src
img decode
img srcset
(etc...)
```
It was a little distracting and hard to find the source of the logs because the console.log in my build was wrapped by some other code, so the stack trace was obscured. I imagine the logs help with development of this component but maybe not needed in the distributed code. May I suggest one of the following changes to the Angular component?
1. Remove the logs
2. Add an opt-in debug log mode
3. Keep the logs but prefix with `unpic` or some other unique label so it's easy to identify the source
I am submitting this PR with approach 1 just because that is the simplest to prepare for me.

fix(angular): remove debug logs

---

packages/svelte/src/lib/image.svelte

This package is great! We are using it in our Sveltekit app. One problem we have run into though is that due to Sveltekit's heavily reliance on Client Side rendering we can run into some weird situations where it shows the old image for a little bit when navigating to a new page.
I think it is a bit out of the scope of this package to handle all of this for us, but I think adding the load event for the image will at least give us the ability to fix it on our side by listening for when we get the image. That way when src changes we could set style opacity 0 and then set to 1 on load.

[Svelte] Forward load listener on Svelte Component

---

README.md
docs/src/content/img/react.mdx
packages/core/src/core.ts
packages/react/README.md

Currently if an image does not match a CDN we don't apply any styles. This is unexpected. This PR ensures we apply styles in all cases.
Fixes #360

fix(core): add styles to images without transformers

---

examples/webc/package.json
packages/svelte/package.json
packages/webc/package.json
pnpm-lock.yaml

Pins the dependency because of https://github.com/Tbhesswebber/style-object-to-css-string/issues/27 
Fixes #392

fix(svelte): pin style-object-to-css-string

---

packages/react/src/camelize.ts

When using the `priority` prop with @unpic/react I would get the following console error: 
```
Warning: Invalid DOM property `fetchpriority`. Did you mean `fetchPriority`?
```
Looking at the DOM confirms that the property is being added without any capitalization as 'fetchpriority'. I assumed adding it to `fixedMap` was the right approach (and tested locally to confirm the correct property is used) but happy to just create an issue if you'd rather solve another way!

fix: Add 'fetchpriority' to fixedMap in camelize.ts

---

packages/vue/src/image.vue

Hello :wave: 
This PR fix #436 and fix https://github.com/nuxt-modules/cloudinary/issues/181 . 
When using `useAttrs()`, it doesn't disable attribute inheritance in a vue component. Since `transformer` isn't declared as a prop, vue will try to render it as an attribute.
It doesn't matter server-side thanks to vue/server-renderer which clean the html. However there's no cleaning client-side so vue will render `transformer` as an attribute.

fix(vue): add transform to props list

---

docs/src/content/docs/lib/index.md

Updated the list of supported CDNs [in the docs](https://unpic.pics/lib/). Added:
```diff
+ ImageEngine
+ ImageKit.io
+ Cloudimage
+ Uploadcare
+ Supabase
```

chore(docs): update the list of supported CDNs

---

packages/react/src/camelize.ts

When https://github.com/facebook/react/pull/25927 was merged it meant that React would accept `fetchPriority` as a prop. Unfortunately it then wouldn't accept `fetchpriority` anymore. This would lead to scary error messages in dev or SSR. In Next.js there's no way to know which version you're using, because Next.js reports both versions as 18.x, even when actually using the bundled experimental version that includes this change. The upshot is that in Next.js, pages router needs `fetchpriority` and app router needs `fetchPriority`. The best way to detect which one you're using is to look for the existence of `use()`. React I love you but you're bringing me down.
Fixes #425

fix(react): handle fetchpriority vs fetchPriority

---

.changeset/cuddly-balloons-hug.md
packages/svelte/package.json

The `svelte` field is a [legacy field](https://svelte.dev/docs/kit/packaging#Anatomy-of-a-package.json-svelte). With the latest version of vite and vitest, it didn't recognize the export when it was just `svelte`. Adding the default export got it to be recognized.
The error before this was this:
```
Error: Failed to resolve entry for package "svelte-media-queries". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@unpic/svelte" package
```

fix: add default export

---

.github/workflows/e2e.yml

GH Actions runners have been [upgraded to 2404](https://github.com/actions/runner-images/issues/10636), which no longer include the Netlify CLI. We're using this for e2e tests, so this PR manually installs it.

ci: install Netlify CLI in gh actions

---

.changeset/smart-jokes-serve.md
packages/astro/src/service/base.ts
packages/astro/test/astro.test.ts

Hey Matt 👋 
I've looked into https://github.com/ascorbic/unpic-img/issues/771 again as my images used in MDX pages were still broken during development ([example usage](https://github.com/LekoArts/portfolio-v3/blob/4ee1d92bc14193335df2db714a61f786dcf20535/src/pages/about.mdx#L11)).
I've looked at https://github.com/ascorbic/unpic/blob/5989f6334a751ba4ad5ace4804455a641f3b840c/src/transform.ts#L106-L109 and noticed that for Astro's usage of `transformUrl()` only the first parameter is passed. I assume the old usage is from this breaking change: https://github.com/ascorbic/unpic/blob/5989f6334a751ba4ad5ace4804455a641f3b840c/UPGRADING.md#L16-L41
So `transformOptions.cdnOptions` doesn't do anything anymore. By passing the `providerOptions` as third arg to `transformUrl()` the image used the …

fix(astro): Use correct `endpoint` option
